apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      serviceAccountName: aws-cost-exporter
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        {{- if .Values.args }}
        args:
          {{- range .Values.args }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
        env:
        - name: TAGS_DISCOVERY_URL
          value: http://aws-cost-exporter-tags-discovery:5000
        - name: MODE
          value: cost_provisioning
        {{- if .Values.costExporterEnv }}
          {{- range $key, $value := .Values.costExporterEnv }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        {{- if .Values.env }}
          {{- range $key, $value := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        volumeMounts:
            - name: data
              mountPath: /data  # Adjust the mount path as needed
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-metrics-store
